pyOpenSci/pyosMeta

parse-contributors.py
Small pull request to make an import vent during PyCon23 Sprint to address as part of #8 
Pair programming with @luizirber
=> Extending list of json files that are being parsed to include the update-web-metadata repo

.env-default, .gitignore, README.md, parse-contributors.py, parse_review_issues.py, requirements.txt, src/pyosmeta/file_io.py, src/pyosmeta/parse_issues.py, update_reviewers.py
This PR provides an extension to the PR for issue #21 and contains some improvements for the initial project setup and project dependencies management by;
- Cleaning up the requirements.txt and adding required dependencies
- Integrating a `.env` file and usage for ALL project variables configuration
- Adding a check for successful API requests
- Updates README.md
- Follow the updated README.md to setup the project.
- Run a project script and ensure NO errors are reported. 
- Special thanks to the PyCon2023 organisers, especially the sprint organisers for the opportunity and encouragement to contribute.
- Special thanks to @lwasser for the encouragement, guidance and leadership in making all this possible.
- Thanks to @bbulpett for the initial PR for issue #21.
=> This extends PR from issue: #21

.gitignore, README.md, parse-contributors.py, src/pyosmeta/contributors.py
closes #9 essentially this will allow us to avoid updating the users name so we can manually update that in our website!
=> Update: readme notes & feat - don't update name if exists on website

.devcontainer/devcontainer.json
=> new config

parse-contributors.py, src/pyosmeta/contributors.py
Essentially previously all users were getting assigned to peer review even if they did not participate in peer review. this fixes the bug causing that issue.
=> Fix: small bugs in assigning contrib type

README.md, parse-contributors.py, src/pyosmeta/contributors.py
This is a small PR that fixes some minor bugs in our metadata workflow.
=> Fix: readme duplication, remove print statements

.gitignore, README.md, src/pyosmeta/cli/parse_contributors.py, src/pyosmeta/cli/parse_review_issues.py, src/pyosmeta/cli/update_reviewers.py, src/pyosmeta/contributors.py, src/pyosmeta/file_io.py, src/pyosmeta/parse_issues.py
This is a draft PR with ugly code that starts the process of updating review information and adding reviewers / editors to our peer review contrib list
=> Numerous bug fixes and update reviewers script

README.md, src/pyosmeta/cli/update_contributors.py, src/pyosmeta/cli/update_reviews.py, src/pyosmeta/parse_issues.py
This adds the final needed step an  update-arg that we will use for manual updates of ALL user and review info
=> Cleanup: Add update arg & update docs

src/pyosmeta/parse_issues.py
closes #51 - this just adjusts the date to be year-month-day to make jekyll happier
=> Fix date format to make jekyll happy

src/pyosmeta/parse_issues.py
=> Fix: categories should be lower case with a dash

src/pyosmeta/cli/parse_history.py, src/pyosmeta/cli/update_contributors.py, src/pyosmeta/cli/update_review_teams.py, src/pyosmeta/contributors.py
A small pr to parse commit history and get the date each contrib was added (generally). this will help us sort users on the website, highlight new people and also create plots of contributors over time!!
=> Feat: get user added date from commit history

.gitignore, README.md, pyproject.toml, requirements.txt, src/pyosmeta/file_io.py
This addresses #75 
it removes the deprecated method and replaces with the preferred object-based approach
it also fixes issues in the dependency list and updates README instructions accordingly. 
finally it moves our build to hatchling as i'm really enjoying working with it
=> Fix: pyproj toml deps and small package update

CHANGELOG.md, CONTRIBUTING.md, src/pyosmeta/cli/update_review_teams.py
Just a few minor text changes. Also be sure to update precommit so it's >3.2 with the new updates!
=> Fix: minor text updates following carols enhancements

development.md
Missed this after adding your tutorial link suggestion.
=> Fix grammar in devguide

src/pyosmeta/utils_clean.py
This PR improves the naming of function inputs for cleaning utilities by making the inputs and docstrings more generic.
Since all functions are used, this PR also removes the TODO in the module docstring.
This should help future contributors.
=> Refactor cleaning utility input names to be consistent and update docstrings

tests/conftest.py, tests/unit/test_github_api.py
This is a small pr where i added a test and cleaned up the fixtures a bit.
=> Fix tests2

src/pyosmeta/cli/update_review_teams.py
I made a mistake - and forgot to test the last script in our workflow. this just updates that script so it runs as expected given the recent refactor.
=> Fix: small bug - forgot to update last script

CHANGELOG.md
=> Add changelog for v0.2.4

.github/workflows/main.yml
Testing this action to see if it automatically adds an issues to the help-wanted board
=> Add: help-wanted label action

.flake8, .pre-commit-config.yaml, pyproject.toml, src/pyosmeta/cli/parse_history.py, src/pyosmeta/cli/process_reviews.py, src/pyosmeta/cli/update_contributors.py, src/pyosmeta/cli/update_review_teams.py, src/pyosmeta/contributors.py, src/pyosmeta/file_io.py, src/pyosmeta/github_api.py, src/pyosmeta/models.py, src/pyosmeta/parse_issues.py, src/pyosmeta/utils_clean.py, tests/conftest.py, tests/unit/test_github_api.py, tests/unit/test_parse_categories.py, tests/unit/test_utils_clean.py, tests/unit/test_utils_parse.py
Fixes #152
I used https://pypi.org/project/flake8-to-ruff and added line-length and isort config.
=> Adopt ruff

src/pyosmeta/file_io.py
=> Fix undeclared fix_indent

CHANGELOG.md
This pr just updates the changelog. i'm going to bump the version again and retry our build!
=> [Release] v0.1.7 -- pyosMeta

src/pyosmeta/models/base.py
Closes #182 
this is just a simple fix to support updating our advisory council + adding a new emeritus status so people are recognized for both current & past contributions ✨ .
=> Fix: add emeritus_Advisory field

CHANGELOG.md
Thank you again @sneakers-the-rat  ✨
=> Release 1.3.2 -- this should fix our current build problems!! 

tests/unit/test_github_api.py
This PR adds an updated test after the changes from #193 before the SciPy sprint.
=> Update api endpoint test to check for any valid endpoint

CHANGELOG.md, LICENSE
This is an update to the changelog to support our next release!
=>  ✨ Release v1.3.4 update changelog ✨ 

CHANGELOG.md
This is a small pr to update the changelog before a patch release.
=> Release 1.3.5

.pre-commit-config.yaml, _data/contributors.yml, _data/packages.yml
This setups the contrib workflow to add files
=> add: data files to repo

CHANGELOG.md
=> Release 0.4 :sparkles:

README.md
Add one line for project information that is fairly static
Add a second line for CI and coverage/tests
=> Reorder badges and add more CI badges in README

.github/workflows/publish-pypi.yml, CHANGELOG.md
This pull request updates the `CHANGELOG.md` file to document the new v1.7.3 release and to improve consistency in section headings throughout the changelog
=> Release notes for 1.7.3

CHANGELOG.md, src/pyosmeta/parse_rss.py
=> bugfix: remove newline in rss feed stubs
