.github/workflows/run-script.yml, .github/workflows/test-run-script.yml, .pre-commit-config.yaml, README.md, parse-contributors.py, parse_review_issues.py, src/pyosmeta/contributors.py, src/pyosmeta/file_io.py, src/pyosmeta/parse_issues.py, update_reviewers.py
This simplifies clients that are calling our scripts here, such as https://github.com/pyOpenSci/pyopensci.github.io/blob/main/.github/workflows/update-packages.yml
It is in response to the path being wrong with a recent effort to update packages, https://github.com/pyOpenSci/pyopensci.github.io/actions/runs/5562999146/jobs/10161656266#step:5:69
```
Notice:  To update, run: pip install --upgrade pip
/home/runner/work/pyopensci.github.io/pyopensci.github.io
python: can't open file '/home/runner/work/pyopensci.github.io/pyopensci.github.io/scripts/parse_issue_metadata.py': [Errno 2] No such file or directory
```
I'm mixed on whether this is the "best" approach. It's nice that it separates the python environment stuff over here, away from the repos that are just web content. At the same time, …
=> reusable workflow for calling scripts

src/pyosmeta/cli/update_contributors.py, src/pyosmeta/cli/update_review_contribs.py, src/pyosmeta/cli/update_reviews.py
This is a tiny set of fixes to ensure the output yml files are added to our website correctly.
=> Path cleanup and only export yml in final step

src/pyosmeta/cli/update_reviews.py, src/pyosmeta/parse_issues.py
Sometimes date_accepted is missing and others it's just wrong format. this cleans up that entry in our metadata for reviews.
=> Fix date_Accepted and keep running if it's missing

src/pyosmeta/parse_issues.py
closes https://github.com/pyOpenSci/update-web-metadata/issues/50
=> Remove duplication of fork count

pyproject.toml, src/pyosmeta/cli/parse_history.py, src/pyosmeta/cli/update_contributors.py
this should fix the current CI failure in the website repo. it makes updating dates across all users optional (and this should only be run locally)
=> Fix: remove date parses running automatically

src/pyosmeta/parse_issues.py, src/tests/test_parse_user_names.py
#70 
I've created a function outside `ProcessIssues()` class for parsing usernames. Additionally, I've written a simple unit test. I didn't check the process of updating webpage data because I don't have a Github Token for it (**maybe we need some toy repository to test this package?**).
🐢
=> Update parse usernames process

README.md, src/pyosmeta/parse_issues.py
this is a minor fix that strips markdown from package names. This could be a helper that is useful for other fields as well in the future.
=> Fix: clean up markdown from package name

.github/workflows/run-tests.yml, CHANGELOG.md, README.md, development.md, pyproject.toml, src/tests/test_parse_user_names.py
closes #89 
This is a small PR to begin moving to hatch scripts for easier test runs and automation. 
i also moved us over to pytest to take advantage of pytest.parametrize
=> Fix: move to hatch scripts for tests and move to pytest

.pre-commit-config.yaml, src/pyosmeta/cli/update_review_teams.py, src/pyosmeta/contributors.py, src/pyosmeta/parse_issues.py
This PR updates the pre-commit hook for black to 24.2.0. Black 24.1 introduced the stable style for 2024. This PR also fixes the files that need updating to that style.
=> Bump black pre-commit hook and update file formats for black 2024 style

src/pyosmeta/__about__.py
Removes `__about__.py` that is no longer needed to set a version.
=> Remove unneeded file now that hatch is used for packaging

CHANGELOG.md, src/pyosmeta/parse_issues.py, tests/unit/test_parse_categories.py
closes #105 
Opening as a draft as it still needs tests but this adds a validation step to categories to ensure they are added to the final yaml file in a clean format with only dashes in between words for easier web parsing.
=> Fix: Add categories validator to model

pyproject.toml
This PR adds dev dependencies as optional dependencies and makes minor style changes.
Developers can now run `pip install ".[dev]"` or `pip install -e ".[dev]"` to install dev tools locally.
We can set up a dev environment for hatch in a separate PR.
=> Update optional dependencies and edit pyproject.toml

.github/workflows/run-tests.yml, .gitignore, CHANGELOG.md, README.md, development.md, pyproject.toml
closes #97 
Setup codecov. for some reason i can generate an in terminal report but rendered reports are failing for me locally.  but all of the other pieces are setup for this to work
=> Fix: add test coverage

.github/workflows/publish-pypi.yml, CHANGELOG.md
this closes #100 #82
NOTE: i haven't set this up before with hatch but because hatch is using setuptools_scm i suspect it's the same workflow. let's see how this runs.
=> Fix: Update publish pypi workflow to use hatch

.github/workflows/publish-pypi.yml
This is a tiny pr that should fix test pypi failing (as it did on @willingc last commit). if we merge this test pypi should recieve a new build of pyos meta (which is not published there yet).
=> Fix: test pypi trusted workflow setup, remove token

.github/workflows/publish-pypi.yml
https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#defining-a-workflow-job-environment i'm not actually sure this is the right location for these permissions. or how to test. but i can ask someone in our slack to review?? or do you know @willingc i've not had to setup such permissions before but i've also not published using trusted publisher before i've always used a token.
=> Fix: add permissions to publish

.flake8, .gitignore, .pre-commit-config.yaml
Addresses #78.
This PR updates and documents the following configuration files:
- .gitignore (use standard Python gitignore and move pyosMeta specific items to end)
- .flake8 (explain ignored rules and add a code complexity check)
- .precommit.config.yaml (improve comments for maintainability and new contributor friendliness)
=> Update gitignore, flake8, and pre-commit config files

.github/workflows/publish-pypi.yml, .gitignore, CHANGELOG.md, src/pyosmeta/cli/process_reviews.py, src/pyosmeta/parse_issues.py, tests/unit/test_review_model.py
Rather than fixing the entire thing i'm working towards cleaning up the parse_issues method. This is a small fix that 
1. adds a field alias to pydantic so there's not a random date field cleanup step in an unexpected place. 
2. adds a small test to ensure the both aliases defined in the model work 
i'm guessing there are better ways to setup tests like this but it's a start and i'm trying to keep this contained. this addresses #91 in (a very small) part.
=> Fix: field alias for date_accepted field

CHANGELOG.md
This PR adopts the ["Keep a Changelog"](https://keepachangelog.com/en/1.1.0/) format. This will be useful if we decide to automate changelogs in the future. It also adds some shoutouts for contributions. The changelog itself is not comprehensive of all changes, but links to all changes.
=> Draft February 2024 changelog

CHANGELOG.md, src/pyosmeta/parse_issues.py
This will close #94 
the simple fix to the pagination issue is to just change the api endpoint to increase from the default 30 to 100 per page. this PR implements that fix. 
In a separate fix we can add pagination.
=> Fix: parse up to 100 issues in a request

CHANGELOG.md, src/pyosmeta/models.py, src/pyosmeta/parse_issues.py, src/pyosmeta/utils_clean.py, src/pyosmeta/utils_parse.py, tests/unit/test_parse_user_names.py
closes #121 
Here i moved parse_names to a new utils_parse.py module. i also renamed clean to utils_clean.py. i lead with utils to avoid confusing parse_utils with parse_issues and then the two utils modules sort nicely together in the package
=> Fix: rename util modules

.github/workflows/publish-pypi.yml, .github/workflows/run-script.yml
Partially addresses #113 
This PR makes the versions used by checkout and python actions the same across all files. This should remove the warnings seen on some workflows about NodeJS 16 deprecation.
=> Update github actions to resolve nodejs 16 warnings

tests/unit/test_utils_clean.py, tests/unit/test_utils_parse.py
This small PR breaks up the existing test file for utilities into two test files following the refactor in #121 and #120. No tests were changed.
=> Split utilities test file into two to match the source files

CHANGELOG.md, development.md, src/pyosmeta/cli/process_reviews.py, src/pyosmeta/contributors.py, src/pyosmeta/github_api.py, src/pyosmeta/parse_issues.py, tests/conftest.py, tests/unit/test_github_api.py, tests/unit/test_parse_categories.py
this is the first part of addressing #125 
it moves all of the gh methods from parse issues into a new module. 
tests are still needed so opening as a draft.
=> Fix: Move all of the github things to a new module for easier maintenance

CHANGELOG.md, src/pyosmeta/cli/update_contributors.py, src/pyosmeta/models.py
closes #133 
This is the last step (i think) in our partner process workflow update. It adds a partners field to the contributor model as format list. it also adds support for the emeritus_editor field so we can acknowledge all past editors.
=> Fix: add partners to contributors

CHANGELOG.md, pyproject.toml, src/pyosmeta/cli/update_contributors.py, src/pyosmeta/contributors.py, src/pyosmeta/file_io.py, src/pyosmeta/github_api.py, tests/conftest.py, tests/unit/test_contributors_module.py, tests/unit/test_github_api.py
This should close #125 it's the second half of migrating all of our github methods into the github_api module. 
It also adds some docstrings and clarification in some of the methods. 
i am going to add a few tests as well once we know everything is passing as is.
=> Fix: refactor github methods out of contributor mod

CHANGELOG.md, src/pyosmeta/github_api.py
A pr to support pagination when we fetch issues. 
Working locally on summary values for total submissions over time, etc
=> Add: pagination support for issue requests

.github/workflows/publish-pypi.yml, CHANGELOG.md
This addresses most of #113 but it doesn't add sigstore security. i think so we can release this week we move that specific step to a new issue and tackle it in april. i'll open the issue now! i can't test this until i create a new release
=> Fix: separate build and publish steps in CI

CHANGELOG.md, README.md, src/pyosmeta/cli/update_review_teams.py, src/pyosmeta/utils_clean.py, tests/unit/test_github_api.py, tests/unit/test_update_review_teams.py, tests/unit/test_utils_clean.py
This is a small bug fix. this action hasn't been running in a few weeks because of this.
=> Fix: bug in github username for reviewers)

.github/workflows/run-tests.yml
=> Test cli on pull requests

.github/workflows/publish-pypi.yml
Addresses failure seen in https://github.com/pyOpenSci/pyosMeta/actions/runs/9765882417/job/26957638716, "Unable to find any artifacts for the associated workflow".  We need to use consistent versions of the upload and download actions.
=> Fix sigstore job

src/pyosmeta/models/base.py, src/pyosmeta/parse_issues.py, tests/data/reviews/partnership_astropy.txt, tests/unit/test_parse_categories.py, tests/unit/test_parse_issue_header_methods.py
Fix: https://github.com/pyOpenSci/pyosMeta/issues/186
sorry this is coming so late today, i have been helping everyone else will stuff all day long and haven't even gotten to any of my own work yet lmao, but since i caused this bug i wanted to fix ASAP.
so here's fix as discussed 
- **model** - used  string enum (python 3.10 doesn't have `enum.StrEnum`) instead of a `Literal` because in the future it would be nice to be able to add annotations like the text that comes after the key in the template currently so that we can generate the review template directly from the model. It does the same thing - the pydantic model will validate and throw an error there if there's any value that isn't in that enum. 
- **get_categories** - since the same method `get_categories` is used for parsing a …
=> fix parsing of partnerships

src/pyosmeta/models/base.py, src/pyosmeta/parse_issues.py, tests/integration/test_parse_issues.py
Fix: https://github.com/pyOpenSci/pyosMeta/issues/188
sorta self explanatory, we can keep the whole `Issue` object if we want, i just figure we sorta want to keep the review `yaml` tidy-ish and wasn't sure if we would want to use any of those other fields. if we want it it would just be a matter of removing the validator and changing the field type.
=> get labels from issue metadata

CHANGELOG.md, src/pyosmeta/github_api.py, src/pyosmeta/models/base.py, src/pyosmeta/parse_issues.py
closes #192 
Right now i was trying to pull all issues which meant it was grabbing issues that were NOT actually review issues. I decided it was better to be explicit. This pr thus fixes two things
1. it allows us to parse through issues and look for issues that contain a specific label. By default the rest endpoint returns issues with ALL labels included. But we wanted the select an issue based upon a specific label occuring within a set of labels. This implements that by filtering issues. GraphQL i think has an OR option? but i just am trying to get the peer-review-metrics running again with this pr. 
2. This pr also adds an alias for repo_link to support the presubmission template
=> Fix: fix label parsing

src/pyosmeta/models/base.py
This is a small fix to ensure that emeritus advisory and advisory roles:
1. default to false
2. always have a bool value which should default to false
3. should not be changed by the code if the value in the data is true (i think this was just a tiny bug that i found).
=> fix: advisory_council should default to false

tests/unit/test_contributors_module.py
This PR brings the coverage of `contributors.py` from 38% to 94%.
=> Add unit tests using pytest for contributors module

CHANGELOG.md, src/pyosmeta/github_api.py, tests/unit/test_github_api.py
this is a draft issue that adds support for both issues and pr's into pyos meta. this will allow us to more easily process metrics that we need for reporting.
=> feat: support for issues ++ prs ✨  in pyosmeta

CHANGELOG.md, src/pyosmeta/cli/update_contributors.py
closes #197 
this adds repos others have contributed to. I'm doing this because i want to update our current metrics and they don't currently capture all of the contributions going on in our org because not all of the repos are parsed in the workflow!
=> Add: additional repos to parse contributors

src/pyosmeta/github_api.py, tests/unit/test_github_api.py
This pr adds an optional after_date to the rest call. This will allow us to build a workflow that tracks user contributions over time which is another metrics of pyOS community growth. Prs in particular represent users with some "ownership" and investment in contributing to pyos!
=> feat: Add after date to api call 

CHANGELOG.md, src/pyosmeta/cli/update_review_teams.py, src/pyosmeta/contributors.py, src/pyosmeta/file_io.py, src/pyosmeta/models/base.py, tests/conftest.py, tests/integration/test_review_model.py, tests/unit/test_github_api.py, tests/unit/test_update_review_teams.py
This fixes parsing of the EiC role (when it exists) i our review metadata population.
There were a few issues
✅ the field serializer and the validator were not setup to include packages_eic 
✅ eic wasn't a role in our contrib_roles object for the review model so that field wasn't being processed. As such when Chiara added her name which was missing, it was deleted in the next bot update. This is now fixed
This pr doesn't have tests yet but we should add some integration tests that ensure contrib data are processed correctly. and then another test to check serialization to yaml
=> fix: make sure eic roles are populated correctly

CHANGELOG.md, src/pyosmeta/models/base.py, src/pyosmeta/models/github.py, src/pyosmeta/parse_issues.py, tests/integration/test_parse_issues.py
For https://github.com/pyOpenSci/pyopensci.github.io/issues/320
This adds a new `active: bool = True` field to the `ReviewModel` class to track whether a package/review is archived or not. All reviews default to an `active=True` status and are only set to `active=False` if the `archived` label is applied to the original review.
In tandem with these changes, I've added a new "archived" label in the software-submissions repository. You can view this label and currently archived packages here: https://github.com/pyOpenSci/software-submission/issues?q=label%3Aarchived
If that specific label is applied to a review, then each time the pyosMeta `update-reviews` routine is run, it will discover that and set the `active` status to `False`
=> feat: add archive label and active status to ReviewModel

.github/workflows/publish-pypi.yml
closes #264 
i can only conclude that the issue was related to the sigstore action as upload and download artifact are current.
=> Fix: update deprecated sigstore action

tests/data/reviews/missing_community_partnerships.txt, tests/integration/test_parse_issues.py
Just had this extra test lying around from when I was working on https://github.com/pyOpenSci/pyopensci.github.io/issues/560#issuecomment-2660714149
=> Test missing community partnerships section

src/pyosmeta/cli/process_reviews.py, src/pyosmeta/github_api.py
Hot fix to have the `update-reviews` script fail on CI if errors are encountered when processing reviews
This is a hotfix in that I want to also update this script to ensure that no package is ever deleted when updating the reviews... that may be more involved
ref https://github.com/pyOpenSci/pyopensci.github.io/pull/599
=> [Hotfix] update reviews script fail on error

.github/workflows/test-update-contribs.yml, .pre-commit-config.yaml
Same as https://github.com/pyOpenSci/pyopensci.github.io/pull/603
This opts into automatically fixing PRs with pre-commit CI and removes `pre-commit/action` from the GitHub Actions workflows
- The  `pre-commit/action` GitHub Action is in maintenance only mode and they recommend swithing to pre-commit CI
- We previously used `pre-commit/action` to automatically reformat the YAML data files generated during the automated data update jobs.
- This PR will instead have those jobs automatically update the data, then pre-commit will automatically fix the formatting as a second commit.
This will remove the confusing error annotation we're seeing on the data update CI jobs since the pre-commit check technically fails since it reformats the YAML data files after they are generated
=> [Proposal] Autofix PRs with pre-commit CI

.github/workflows/test-update-contribs.yml, .pre-commit-config.yaml
Per https://github.com/pyOpenSci/pyosMeta/pull/273#issuecomment-2766668675 only run the autofix pre-commit CI on automated PRs
=> Only use pre-commit ci autofix on automated PRs

.github/workflows/add-help-wanted.yml, .github/workflows/publish-pypi.yml, .github/workflows/run-script.yml, .github/workflows/run-tests.yml, .github/workflows/test-run-script.yml, .github/workflows/test-update-contribs.yml, .pre-commit-config.yaml
Closes #245 
Added zizmor to the `pre-commit-config.yaml` file and fixed the security issues it raised:
- Pinned some actions using their SHA instead of tag. See [zizmor unpinned-uses remediation](https://docs.zizmor.sh/audits/#remediation_19)
- Set `permissions: {}` at the workflow level to disable all permissions by default. See [zizmor excessive-permissions remediation](https://docs.zizmor.sh/audits/#after_2) 
- Add `persist-credentials: false` under `actions/checkout`. See [zizmor persist-credentials](https://docs.zizmor.sh/audits/#after)
- Removed the `script_name_with_args` input due to [template-injection](https://docs.zizmor.sh/audits/#remediation_17). I looked at the actions and noticed the `test-run-script.yml` file was running the `update-contributors` script recently. Let me …
=> ci: Add zizmor to `pre-commit-config.yaml`

CODE_OF_CONDUCT.md, README.md
Copied module docstrings from: 
- parse_history.py
- process_reviews.py 
- update_contributors.py
- update_review_teams.py
into README.md under the Usage section, with slight tweaks. 
Updated code of conduct link to https://www.pyopensci.org/handbook/CODE_OF_CONDUCT.html.
=> Docstrings to docs

.github/workflows/publish-pypi.yml, CHANGELOG.md
closes #286 
This fix removes a duplicate upload to sigstore. The PyPA action by default implements signing.
=> Fix: remove sigstore step from publish build as it's duplicate

CHANGELOG.md, src/pyosmeta/models/base.py, tests/data/reviews/multiple_editors.txt, tests/integration/test_parse_issues.py
I noticed that a number of reviews were failing to parse due to having multiple eic or editors. This fixes that
=> [patch] support list of eic and editors

src/pyosmeta/github_api.py
GREOPy (https://github.com/pyOpenSci/software-submission/issues/227) was accepted 2 days ago. It is one of the first few packages who's repository is not hosted on GitHub (hosted at https://codeberg.org/JPHackstein/GREOPy) which means we cannot collect metrics for it (stars, issues count, etc). We'd need to implement a mechanism specific to the hosting service to collect metrics like these (specifically https://codeberg.org/ in this case)
This PR bypasses collecting metrics for repositories that are not hosted on GitHub until we can get around to creating a mechanism that would collect these metrics from sites other than GitHub
=> [Patch] bypass repository metrics when not hosted on GitHub
